# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push

jobs:
  build:
    env:
      NODE_ENV: development
      NETWORK: regtest
      FEE: 2
      LOGLEVEL_ERROR: ""
      LOGLEVEL_WARN: ""
      LOGLEVEL_HTTP: ""
      LOGLEVEL_INFO: ""
      LOGLEVEL_DEBUG: ""
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        redis-version: [6.2.5]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Start Redis v${{ matrix.redis-version }}
        uses: superchargejs/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - run: npm install
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run build
